# Generated by Django 3.2.16 on 2023-06-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AntilibraryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("slug", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("cover_image", models.CharField(max_length=1000)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AntilibraryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("slug", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="AntilibraryBookCategoryMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.antilibrarybook",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcast.antilibrarycategory",
                    ),
                ),
            ],
        ),
    ]
