# Generated by Django 3.2.16 on 2023-06-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antilibrarycategory",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
