# Generated by Django 3.2.16 on 2023-07-02 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_quote_quoteperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
