# Generated by Django 3.2.16 on 2023-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0004_quote_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("slug", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("text", models.TextField()),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
