# Generated by Django 3.2.16 on 2023-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="thumbnail",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="date_created",
            field=models.DateField(),
        ),
    ]
