# Generated by Django 3.2.16 on 2023-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0006_auto_20230709_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="description",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
