# Generated by Django 3.2.16 on 2023-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0007_dispatch_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatch",
            name="text",
        ),
        migrations.AddField(
            model_name="dispatch",
            name="url",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
