# Generated by Django 3.2.16 on 2023-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0008_auto_20230726_1232"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("thumbnail", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("date_created", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Dispatch",
        ),
    ]
