# Generated by Django 3.2.16 on 2023-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0009_auto_20230726_1831"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("slug", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=2000)),
                ("headshot", models.CharField(max_length=1000)),
                ("bkg_colour", models.CharField(max_length=10)),
                ("audio_url", models.CharField(max_length=1000)),
                ("date_created", models.DateField()),
                ("eipsode_number", models.IntegerField(default=1)),
                ("transcript", models.TextField(default="No Transcript Available")),
            ],
        ),
    ]
