# Generated by Django 3.2.16 on 2023-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0010_podcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
