# Generated by Django 3.2.16 on 2023-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0011_video_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="antilibrarybook",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="podcast",
            name="audio_url",
            field=models.CharField(max_length=10000),
        ),
    ]
