# Generated by Django 3.2.16 on 2023-08-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0012_auto_20230826_0708"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antilibrarybook",
            name="description",
        ),
    ]
