# Generated by Django 3.2.16 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0013_remove_antilibrarybook_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="transcript",
            new_name="summary",
        ),
        migrations.AddField(
            model_name="podcast",
            name="resources",
            field=models.TextField(default="No Resources Available"),
        ),
    ]
