# Generated by Django 3.2.16 on 2023-10-23 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0014_auto_20231012_1909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="resources",
            field=ckeditor.fields.RichTextField(default="No Summary Available"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="summary",
            field=ckeditor.fields.RichTextField(default="No Summary Available"),
        ),
    ]
