# Generated by Django 3.2.16 on 2024-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0015_auto_20231023_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='season_number',
            field=models.IntegerField(default=1),
        ),
    ]
