# Generated by Django 3.2.16 on 2024-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0016_podcast_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='antilibrarybook',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
