# Generated by Django 3.2.16 on 2024-05-22 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0018_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='transcript',
            field=ckeditor.fields.RichTextField(default='No Transcript Available'),
        ),
    ]
