# Generated by Django 3.2.16 on 2024-06-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0019_podcast_transcript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='url',
            new_name='body',
        ),
    ]
