# Generated by Django 3.2.16 on 2024-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0020_rename_url_insight_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
